AWSTemplateFormatVersion: 2010-09-09
Outputs:
  DynamoDBTableArn:
    Description: The ARN of your DynamoDB Table
    Value:
      Fn::GetAtt:
      - DynamoDBTable
      - Arn
  DynamoDBTableStreamArn:
    Description: The ARN of your DynamoDB Table Stream
    Value:
      Fn::GetAtt:
      - DynamoDBTable
      - StreamArn
  S3Bucket:
    Description: The S3 Bucket where the files are stored
    Value:
      Ref: S3FileStorage
Parameters:
  TableName:
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: Required parameter. Must be characters only. No numbers
      allowed.
    Default: yourTableName
    Description: (Required) The name of the new DynamoDB table you want to create
      and save to. Minimum 3 characters
    MaxLength: 50
    MinLength: 3
    Type: String
Resources:
  DynamoDBTable:
    Properties:
      AttributeDefinitions:
      - AttributeName:
          Fn::Sub: ${TableName}Id
        AttributeType: S
      KeySchema:
      - AttributeName:
          Fn::Sub: ${TableName}Id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName:
        Ref: TableName
    Type: AWS::DynamoDB::Table
  LambdaSave:
    Properties:
      CodeUri: s3://s3-lambda-save-dynamodb-bucket/3e71febfc419d1e90de4fe80f9ffe6b7
      Environment:
        Variables:
          PRIMARY_KEY:
            Fn::Sub: ${TableName}Id
          TABLE_NAME:
            Ref: TableName
      Events:
        S3BucketEvent:
          Properties:
            Bucket:
              Ref: S3FileStorage
            Events: s3:ObjectCreated:*
          Type: S3
      Handler: index.handler
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  S3FileStorage:
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
